import {teacherApi,requireTeacher,canTeachRoom,ownedQuestionSet} from './teachers.mjs';
import {resolveTeacherIdentity} from './teacher-auth.mjs';
import {lootStamp} from '../public/snapshots.mjs';
import {teacherCommand,featureView,recordTeamAnswer,claimMission,teamPing} from '../public/session-features.mjs';
import {getProfile,awardProfile,profileRequest,validateCosmetic} from './profiles.mjs';
import {mapInfo,validMap} from '../public/maps.mjs';
import {normalizeLesson,publicLesson,openQuestion,answerQuestion} from '../public/learning.mjs';
import {WEAPONS} from '../public/rules.mjs';
import {makeMatch,setInput,advance,finishTimedMatch} from '../public/engine.mjs';
import {normalizeAppearance} from '../public/appearance.mjs';
import {MAX_PLAYERS,MAX_TEAMS,TEAM_SIZE} from '../public/config.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const nickname=value=>typeof value==='string'&&value.trim()?value.trim().slice(0,18):'ผู้รอดชีวิต';
const validMode=value=>{if(!['solo','squad'].includes(value))fail('เลือกโหมดเล่นเดี่ยวหรือเล่นทีม');return value};
function compactMatch(match,selfId,knownLoot){if(!match)return null;const{...safe}=match;delete safe.navBudget;if(knownLoot===lootStamp(match))delete safe.loot;return{...safe,entities:match.entities.map(actor=>{const e={...actor};delete e.learning;if(e.id!==selfId)delete e.weapons;for(const key of['input','nav','targetId','senseAt','sight','hadSight','botTimer','strafe','stuck','lastInput','downedBy'])delete e[key];return e})}}
function roomView(room,member,revision=0,knownLoot,identity=null){const teacher=canTeachRoom(room,member,identity),features=featureView(room,member,Date.now());if(!teacher)features.report=null;return{snapshotRevision:revision,...features,isTeacher:teacher,code:room.code,id:member.id,mode:room.mode,mapId:room.mapId??'dawn',lesson:publicLesson(room.lesson),...(teacher?{teacherQuestions:room.lesson?.questions}:{teacherQuestions:null}),learning:room.match?(()=>{const e=room.match.entities.find(a=>a.id===member.id),p=e?.learning;return{correct:p?.correct??0,answered:p?.answered??0,total:room.lesson?.questions.length??0,question:p?.startedAt!=null||room.broadcast&&p?.broadcastId!==room.broadcast.id?openQuestion(room,e,Date.now()):null}})():null,results:room.match?.entities.filter(a=>a.human||a.disconnected).map(e=>({id:e.id,name:e.name,correct:e.learning?.correct??0,answered:e.learning?.answered??0,kills:e.kills})),isHost:room.members[0]?.id===member.id,selfTeam:member.team,queue:!!room.queue,startsAt:room.startsAt??null,deadline:room.deadline??null,capacity:MAX_PLAYERS,teamSize:room.mode==='squad'?TEAM_SIZE:1,state:room.match?.state??'waiting',players:room.members.map(a=>({id:a.id,name:a.name,appearance:normalizeAppearance(a.appearance),team:a.team,slot:a.slot,host:a.id===room.members[0]?.id,connected:Date.now()-a.seen<12000})),match:compactMatch(room.match,member.id,knownLoot)}}
function normalizeRoom(room){room.mapId??='dawn';room.lesson??=normalizeLesson();if(room.match){room.match.mapId??=room.mapId;room.match.duration??=room.lesson.durationMinutes*60;room.match.mapRadius??=mapInfo(room.mapId).playRadius}if(room.match)for(const e of room.match.entities){for(let n=e.weapons.length;n<WEAPONS.length;n++)e.weapons.push({ammo:WEAPONS[n].mag,reserve:120,owned:false});e.scopes??=[0,1];e.scope??=1;e.recoil??=0;e.bloom??=0}room.mode??='squad';room.members.forEach((a,i)=>{a.team??=room.mode==='solo'?i:Math.floor(i/TEAM_SIZE);a.slot??=room.mode==='solo'?0:i%TEAM_SIZE});return room}
function authenticate(room,token){const member=room.members.find(a=>a.token===token);if(!member)fail('เซสชันห้องหมดอายุ กรุณาเข้าห้องใหม่',401);return member}
function seat(room,preferred,except){const per=room.mode==='solo'?1:TEAM_SIZE,teams=room.mode==='solo'?MAX_PLAYERS:MAX_TEAMS;if(preferred!==undefined&&(!Number.isInteger(preferred)||preferred<0||preferred>=teams))fail('หมายเลขทีมไม่ถูกต้อง');for(const team of preferred===undefined?Array.from({length:teams},(_,i)=>i):[preferred])for(let slot=0;slot<per;slot++)if(!room.members.some(a=>a.id!==except&&a.team===team&&a.slot===slot))return{team,slot};fail(preferred===undefined?'ห้องเต็มแล้ว (สูงสุด 50 คน)':'ทีมนี้เต็มแล้ว (สูงสุด 5 คน)',409)}
function begin(room,now){if(room.mode==='solo')room.members.forEach((a,i)=>{a.team=i;a.slot=0});room.match=makeMatch({mode:room.mode,humans:room.members.map(a=>({id:a.id,name:a.name,appearance:a.appearance,team:a.team,slot:a.slot})),seed:now>>>0,mapId:room.mapId,duration:room.lesson.durationMinutes*60,educational:room.lesson.enabled});room.startedAt=now;room.deadline=now+room.lesson.durationMinutes*60000;room.lastTick=now;room.startsAt=null;room.pausedAt=null;room.broadcast=null;room.broadcastCount=0;room.resumedAt=0;room.missions=null;room.pings=[]}
function controls(value){const finite=n=>Number.isFinite(n)?n:0;const c=value&&typeof value==='object'?value:{};return{mx:Math.max(-1,Math.min(1,finite(c.mx))),mz:Math.max(-1,Math.min(1,finite(c.mz))),yaw:finite(c.yaw)%(Math.PI*2),pitch:Math.max(-.75,Math.min(.65,finite(c.pitch))),fire:c.fire===true,aim:c.aim===true,scoped:c.scoped===true,sprint:c.sprint===true,revive:c.revive===true,actions:Array.isArray(c.actions)?c.actions.filter(a=>a&&Number.isSafeInteger(a.seq)&&a.seq>0&&['fire','jump','crouch','reload','heal','swap','wall','scope','pickup'].includes(a.type)).slice(-12).map(a=>({seq:a.seq,type:a.type,...(a.type==='pickup'&&a.index!==undefined?{index:Number.isSafeInteger(a.index)&&a.index>=0?a.index:-1}:Number.isInteger(a.index)&&a.index>=0&&a.index<WEAPONS.length?{index:a.index}:{})})):[]}}
async function cleanup(db,now){await db.batch([db.prepare('DELETE FROM room_inputs WHERE expires<?').bind(now),db.prepare('DELETE FROM rooms WHERE expires<? AND queue_mode IS NOT NULL').bind(now),db.prepare('DELETE FROM rooms WHERE code IN (SELECT code FROM rooms WHERE expires<? LIMIT 20)').bind(now)])}
function code(){const bytes=crypto.getRandomValues(new Uint8Array(6)),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return[...bytes].map(b=>alphabet[b%32]).join('')}
async function create(db,input,now,queue,identity){
 if(!queue&&(input.teacher||input.lesson||input.questionSetId))requireTeacher(identity);
 const saved=!queue&&input.questionSetId?await ownedQuestionSet(db,identity,input.questionSetId):null;
 const mode=validMode(input.mode??'squad'),mapId=input.mapId??saved?.mapId??'dawn';if(!validMap(mapId))fail('เลือกแมพที่มีอยู่');
 await cleanup(db,now);const profile=await validateCosmetic(db,input),lesson=normalizeLesson(queue?{enabled:true}:saved?.lesson??input.lesson??{enabled:true});for(let n=0;n<10;n++){
 if(queue){const open=await db.prepare('SELECT code FROM rooms WHERE queue_mode=? AND expires>?').bind(mode+':'+mapId,now).first();if(open){try{return await updateRoom(db,open.code,'join',input,now,identity)}catch(e){if(e.status!==409&&e.status!==404)throw e;continue}}}
 const member={id:crypto.randomUUID(),token:crypto.randomUUID(),profileToken:profile?.token,name:nickname(input.name),appearance:normalizeAppearance(input.appearance),seen:now,team:0,slot:0},room={code:code(),mode,mapId,lesson,queue,teacherOwnerId:!queue&&(input.teacher||input.lesson||input.questionSetId)?identity?.id??null:null,members:[member],match:null,lastTick:now,startsAt:null};
 try{await db.prepare('INSERT INTO rooms (code,data,revision,expires,queue_mode) VALUES (?,?,0,?,?)').bind(room.code,JSON.stringify(room),now+3600000,queue?mode+':'+mapId:null).run();return json({...roomView(room,member,0,undefined,identity),token:member.token},201)}catch(e){if(!String(e).includes('UNIQUE'))throw e}
 }fail('กำลังจัดห้อง กรุณาลองอีกครั้ง',503)}
async function updateRoom(db,code,operation,input,now,identity){let inputWritten=false;for(let attempt=0;attempt<12;attempt++){
 const row=await db.prepare('SELECT data,revision,expires FROM rooms WHERE code=?').bind(code).first();if(!row||row.expires<now)fail('ไม่พบห้อง หรือห้องหมดอายุแล้ว',404);const room=normalizeRoom(JSON.parse(row.data));let member;
 if(!room.match)room.members=room.members.filter(a=>a.token===input.token||now-a.seen<30000);
 if(operation==='join'){if(input.token)member=room.members.find(a=>a.token===input.token);if(!member){if(room.match)fail('แมตช์เริ่มแล้ว กรุณาค้นหาห้องใหม่',409);if(room.members.length>=MAX_PLAYERS)fail('ห้องเต็มแล้ว (สูงสุด 50 คน)',409);const profile=await validateCosmetic(db,input);member={id:crypto.randomUUID(),token:crypto.randomUUID(),profileToken:profile?.token,name:nickname(input.name),appearance:normalizeAppearance(input.appearance),seen:now,...seat(room,input.team)};room.members.push(member)}if(!room.match&&identity&&room.teacherOwnerId===identity.id&&room.members[0]?.id!==member.id){room.members=room.members.filter(a=>a.id!==member.id);room.members.unshift(member)}}else member=authenticate(room,input.token);
 if(room.match?.state==='playing'&&!room.pausedAt&&room.deadline&&now>=room.deadline){room.match.time=room.match.duration;finishTimedMatch(room.match)}
 if(operation==='poll'&&room.match?.state==='playing'){
  if(!inputWritten){await db.prepare('INSERT INTO room_inputs (code,member_id,data,updated,expires) VALUES (?,?,?,?,?) ON CONFLICT(code,member_id) DO UPDATE SET data=excluded.data,updated=excluded.updated,expires=excluded.expires').bind(code,member.id,JSON.stringify({matchId:room.match.id,controls:room.pausedAt?{}:controls(input.controls)}),now,row.expires).run();inputWritten=true}
  // Independent input rows avoid rewriting a 50-player room for every control packet.
  // Compare-and-swap permits only one worker to advance each shared snapshot.
  if(now-room.lastTick<70)return json(roomView(room,member,row.revision,input.knownLoot,identity));
  if(room.pausedAt){member.seen=now;const heartbeats=await db.prepare('SELECT member_id,data,updated FROM room_inputs WHERE code=? AND updated>?').bind(code,now-1500).all();for(const entry of heartbeats.results){const player=room.members.find(a=>a.id===entry.member_id);if(player)player.seen=entry.updated}room.lastTick=now}
  if(!room.pausedAt){const inputs=await db.prepare('SELECT member_id,data,updated FROM room_inputs WHERE code=? AND updated>?').bind(code,now-1500).all();for(const entry of inputs.results){const packet=JSON.parse(entry.data);if(packet.matchId!==room.match.id||entry.updated<(room.resumedAt??0))continue;const actor=room.match.entities.find(a=>a.id===entry.member_id);if(actor?.disconnected){actor.human=true;delete actor.disconnected}setInput(room.match,entry.member_id,packet.controls);const player=room.members.find(a=>a.id===entry.member_id);if(player)player.seen=entry.updated}
  for(const actor of room.match.entities){const owner=room.members.find(a=>a.id===actor.id);if(actor.human&&owner&&now-owner.seen>15000){actor.human=false;actor.input={};actor.disconnected=true}else if(owner&&now-owner.seen<1500&&actor.disconnected){actor.human=true;delete actor.disconnected}}
  const step=Math.min(.75,Math.max(0,(now-room.lastTick)/1000));if(room.match.drop>0&&room.startedAt)room.match.drop=Math.max(.00001,Math.min(6,6-(now-room.startedAt)/1000+step));advance(room.match,step);if(room.startedAt){room.match.time=Math.max(room.match.time,Math.max(0,(now-room.startedAt)/1000-6))}room.lastTick=now;}
 }else member.seen=now;
 if(room.match?.state==='playing'&&!room.pausedAt&&room.deadline&&now>=room.deadline){room.match.time=room.match.duration;finishTimedMatch(room.match)}
 let answerResult=null;if(operation==='configure'){requireTeacher(identity);if(!canTeachRoom(room,member,identity))fail('บัญชีครูเจ้าของห้องเท่านั้นที่แก้ข้อสอบได้',403);if(room.members[0]?.id!==member.id)fail('ครูเจ้าของห้องเท่านั้นที่แก้การตั้งค่าได้',403);if(room.match?.state==='playing')fail('แก้ก่อนเริ่มแมตช์หรือหลังจบเท่านั้น',409);if(!validMap(input.mapId))fail('เลือกแมพที่มีอยู่');room.mapId=input.mapId;room.lesson=normalizeLesson(input.questionSetId?(await ownedQuestionSet(db,identity,input.questionSetId)).lesson:input.lesson);room.teacherOwnerId=identity.id;if(room.match?.state==='ended')room.match=null}
 else if(operation==='question'){if(room.pausedAt)fail('ครูพักห้องอยู่ รอเล่นต่อก่อนเปิดคำถาม',409);if(!room.match||room.match.state!=='playing'||!room.lesson.enabled)fail('ห้องนี้ยังไม่เปิดคำถาม',409);const actor=room.match.entities.find(e=>e.id===member.id);if(actor.status!=='alive')fail('ตอบได้เมื่อยังมีชีวิต',409);openQuestion(room,actor,now)}
 else if(operation==='answer'){if(input.matchId!==room.match?.id)fail('คำตอบไม่ตรงกับแมตช์',409);const actor=room.match.entities.find(e=>e.id===member.id);answerResult=answerQuestion(room,actor,input,now);if(answerResult.earned)recordTeamAnswer(room,actor,answerResult.sourceId)}
 else if(operation==='start'){if(room.teacherOwnerId){requireTeacher(identity);if(!canTeachRoom(room,member,identity))fail('บัญชีครูเจ้าของห้องเท่านั้นที่เริ่มห้องเรียนได้',403)}if(room.members[0]?.id!==member.id)fail('เจ้าของห้องเท่านั้นที่เริ่มแมตช์ได้',403);if(room.match?.state==='playing')fail('แมตช์กำลังเล่นอยู่',409);begin(room,now)}
 else if(operation==='appearance'){if(room.match?.state==='playing')fail('เปลี่ยนชุดได้เมื่อจบแมตช์แล้ว',409);const profile=await validateCosmetic(db,{...input,profileToken:member.profileToken});member.appearance=normalizeAppearance(input.appearance);if(profile)await db.prepare('UPDATE learner_profiles SET appearance=? WHERE token=?').bind(JSON.stringify(member.appearance),profile.token).run()}
 else if(operation==='team'){if(room.mode!=='squad')fail('โหมดเดี่ยวไม่มีทีม');if(room.match)fail('เปลี่ยนทีมได้ก่อนเริ่มแมตช์',409);Object.assign(member,seat(room,input.team,member.id))}
 else if(operation==='leave'){room.members=room.members.filter(a=>a.id!==member.id);if(room.match){const actor=room.match.entities.find(a=>a.id===member.id);if(actor){actor.human=false;actor.input={};actor.name+=' (บอต)'}}}
 else if(operation==='teacher'){requireTeacher(identity);if(!canTeachRoom(room,member,identity))fail('บัญชีครูเจ้าของห้องเท่านั้นที่ควบคุมห้องเรียนได้',403);room.teacherOwnerId=identity.id;teacherCommand(room,member,input,now)}
 else if(operation==='ping')teamPing(room,member,input,now);
 else if(operation==='mission')answerResult=claimMission(room,member,now);
 else if(!['join','poll'].includes(operation))fail('ไม่รองรับคำสั่งนี้',404);
 // Every waiting room starts only through the authenticated owner's start command.
 if(!room.match)room.startsAt=null;
 const queueMode=room.queue&&!room.match&&room.members.length?room.mode+':'+room.mapId:null;
 const result=await db.prepare('UPDATE rooms SET data=?,revision=revision+1,queue_mode=?,expires=? WHERE code=? AND revision=?').bind(JSON.stringify(room),queueMode,Math.max(row.expires,(room.deadline??0)+900000,room.pausedAt?now+room.lesson.durationMinutes*60000+900000:0),code,row.revision).run();
 if((result.meta?.changes??0)>0){if(operation==='answer')await awardProfile(db,room,member);return json(operation==='leave'?{left:true}:{...roomView(room,member,row.revision+1,operation==='poll'?input.knownLoot:undefined,identity),...(answerResult?{answerResult}:{}),...(operation==='join'?{token:member.token}:{})});}
 // Stagger conflicting writers instead of exhausting every request's query budget.
 await new Promise(resolve=>setTimeout(resolve,Math.min(80,4*(attempt+1))+Math.random()*20));
 }fail('ห้องกำลังซิงก์ กรุณาลองอีกครั้ง',409)}
function operationError(error){return /คำถาม|ตัวเลือก|เลือกคำตอบ|ตอบได้|คำถามนี้/.test(error.message)?error.message:'เชื่อมต่อห้องไม่ได้ กรุณาลองอีกครั้ง'}
export async function api(request,env){try{
 const url=new URL(request.url);if(request.method!=='POST')return json({error:'Method not allowed'},405);if(request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)fail('ไม่อนุญาตคำขอจากเว็บไซต์อื่น',403);if(Number(request.headers.get('Content-Length')??0)>64000)fail('คำขอมีขนาดใหญ่เกินไป',413);const raw=await request.text();if(raw.length>64000)fail('คำขอมีขนาดใหญ่เกินไป',413);let input;try{input=JSON.parse(raw)}catch{fail('รูปแบบคำขอไม่ถูกต้อง')}if(!input||typeof input!=='object'||Array.isArray(input))fail('รูปแบบคำขอไม่ถูกต้อง');if(!env.DB)fail('ห้องออนไลน์ยังไม่พร้อม กรุณาลองอีกครั้ง',503);
 if(request.headers.get('Sec-Fetch-Site')==='cross-site'||/(?:^|;\s*)__Host-teacher_session=/.test(request.headers.get('Cookie')??'')&&request.headers.get('Origin')!==url.origin)fail('ไม่อนุญาตคำขอจากเว็บไซต์อื่น',403);
 const operation=url.pathname.split('/').at(-1),now=Date.now();if(operation==='profile')return json(await profileRequest(env.DB,input));const identity=await resolveTeacherIdentity(request,env.DB);if(operation==='create'||operation==='matchmake')return await create(env.DB,input,now,operation==='matchmake',identity);const roomCode=typeof input.code==='string'?input.code.toUpperCase().replace(/\s/g,''):'';if(!/^[A-Z2-9]{6}$/.test(roomCode))fail('กรุณาใส่รหัสห้อง 6 ตัว');return await updateRoom(env.DB,roomCode,operation,input,now,identity);
 }catch(error){if(!error.status)console.error('Room request failed',error.message);return json({error:error.status?error.message:operationError(error)},error.status??(/คำถาม|ตัวเลือก|เลือกคำตอบ|ตอบได้|คำถามนี้/.test(error.message)?400:503))}}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/teachers/'))return teacherApi(request,env);if(url.pathname.startsWith('/api/rooms/'))return api(request,env);return env.ASSETS.fetch(request)}};
