import assert from 'node:assert/strict';
import {makeMatch,damage,setInput,act,tick,advance,view} from '../public/engine.mjs';
import {canStand,groundHeight,BUILDINGS,cameraPosition} from '../public/arena.mjs';
import {WEAPONS} from '../public/rules.mjs';
import {findRoute,clearRoute} from '../public/navigation.mjs';
const humans=Array.from({length:4},(_,i)=>({id:'friend-'+i,name:'Friend '+i}));
const solo=makeMatch();assert.equal(solo.entities.length,16);assert.equal(new Set(solo.entities.map(e=>e.team)).size,16);assert.equal(solo.entities.filter(e=>e.human).length,1);
const squad=makeMatch({mode:'squad',humans});assert.equal(squad.entities.length,16);assert.equal(squad.entities.filter(e=>e.team===0&&e.human).length,4);assert.equal(new Set(squad.entities.map(e=>e.team)).size,4);
const a=squad.entities[0],b=squad.entities[1],enemy=squad.entities[4];squad.drop=0;
damage(squad,a,1000,b);assert.equal(a.hp,100);assert.equal(a.armor,50);
damage(squad,a,1000,enemy);assert.equal(a.status,'down');assert.equal(a.bleed,30);
a.x=0;a.z=0;a.y=0;b.x=1;b.z=0;b.y=0;
for(let i=0;i<80;i++){setInput(squad,b.id,{revive:true});tick(squad,.04)}assert.equal(a.status,'alive');assert.equal(a.hp,45);assert.ok(squad.events.some(e=>e.type==='revived'&&e.id===a.id));
damage(squad,a,1000,enemy);a.bleed=.02;tick(squad,.04);assert.equal(a.status,'dead');
for(const member of squad.entities.filter(e=>e.team===0))damage(squad,member,1000,enemy);assert.ok(squad.entities.filter(e=>e.team===0).every(e=>e.status==='dead'));
const combat=makeMatch();combat.drop=0;combat.loot=[];combat.entities=combat.entities.slice(0,2);const shooter=combat.entities[0],target=combat.entities[1];Object.assign(shooter,{x:7,z:0,y:0,yaw:0,pitch:Math.atan2(1.3-2.55,15.8),aim:true});Object.assign(target,{x:7.62,z:-12,y:0,armor:0,human:true});
act(combat,shooter,'fire');assert.equal(shooter.weapons[0].ammo,WEAPONS[0].mag-1);assert.ok(target.hp<100,'camera crosshair resolves into a damaging muzzle ray');
const hp=target.hp;shooter.shot=0;combat.walls=[{id:42,x:7,z:-5,y:0,hp:250,life:32,parts:[{x:7,z:-5,w:3,d:.3,y:0,h:3}]}];act(combat,shooter,'fire');assert.equal(target.hp,hp);assert.ok(combat.walls[0].hp<250,'cover absorbs bullets');
shooter.weapons[0].ammo=0;act(combat,shooter,'reload');for(let i=0;i<90;i++)tick(combat,.04);assert.equal(shooter.weapons[0].ammo,WEAPONS[0].mag);
const inputs=makeMatch();inputs.drop=0;const p=inputs.entities[0];setInput(inputs,p.id,{mx:100,mz:NaN,pitch:100,actions:[{seq:1,type:'wall'}]});assert.equal(p.input.mx,1);assert.equal(p.input.mz,0);assert.equal(p.input.pitch,.65);const charges=p.wallCharges;setInput(inputs,p.id,{actions:[{seq:1,type:'wall'}]});assert.equal(p.wallCharges,charges,'duplicate network actions do not spend inventory twice');
const bld=BUILDINGS[0],feet=groundHeight(bld.x,bld.z);assert.ok(canStand(bld.x,bld.z+bld.d/2,undefined,.45,feet),'door gap permits player movement');assert.equal(canStand(bld.x-bld.w/2,bld.z,undefined,.45,feet),false,'exterior walls collide');
const obstruction=[{x:0,z:3,w:4,d:.2,y:0,h:4}],cam=cameraPosition({x:0,z:0,y:0,yaw:0,aim:false,crouch:false},obstruction);assert.ok(cam.z<3,'camera stays in front of a wall');
const landing=makeMatch();landing.drop=.02;Object.assign(landing.entities[0],{x:bld.x-bld.w/2,z:bld.z,y:feet+1});tick(landing,.04);assert.ok(canStand(landing.entities[0].x,landing.entities[0].z,undefined,.45,landing.entities[0].y),'landing repairs overlap with a building');
const zone=makeMatch();zone.drop=0;zone.time=500;zone.entities[0].x=100;zone.entities[0].z=0;zone.entities[0].human=true;advance(zone,.5);assert.ok(zone.entities[0].hp<100);assert.ok(zone.events.every(e=>e.type!=='damage'||e.amount>0));assert.equal(view(zone,'you').mode,'solo');
// A teammate must traverse the house through its doors and revive an ally.
const rescue=makeMatch({mode:'squad'});rescue.drop=0;rescue.loot=[];rescue.entities=[rescue.entities[0],rescue.entities[1],rescue.entities[4]];
const fallen=rescue.entities[0],helper=rescue.entities[1],observer=rescue.entities[2];
Object.assign(fallen,{x:bld.x,z:bld.z-5,y:feet,status:'down',hp:0,bleed:30});
Object.assign(helper,{x:bld.x,z:bld.z+5,y:feet});Object.assign(observer,{x:99,z:0,y:groundHeight(99,0),human:true});
for(let i=0;i<550&&fallen.status==='down';i++)tick(rescue,.04);
assert.equal(fallen.status,'alive','bot enters the doorway and revives an ally behind the house');
const start={x:bld.x-9,z:bld.z},end={x:bld.x+9,z:bld.z};const route=findRoute(start,end);
assert.ok(route.length>=2,'blocked straight route gets a detour');let previous=start;
for(const point of route){assert.ok(clearRoute(previous,point),'all smoothed segments keep the player clear of walls');previous=point}
assert.ok(Math.hypot(previous.x-end.x,previous.z-end.z)<1,'detour reaches the requested destination');
const closeRescue=makeMatch({mode:'squad'});closeRescue.drop=0;closeRescue.loot=[];closeRescue.entities=[closeRescue.entities[0],closeRescue.entities[1],closeRescue.entities[4]];
Object.assign(closeRescue.entities[0],{x:bld.x+bld.w/2-1,z:bld.z,y:feet,status:'down',hp:0,bleed:30});
Object.assign(closeRescue.entities[1],{x:bld.x+bld.w/2+1,z:bld.z,y:feet});Object.assign(closeRescue.entities[2],{x:99,z:0,y:groundHeight(99,0),human:true});
for(let i=0;i<550&&closeRescue.entities[0].status==='down';i++)tick(closeRescue,.04);
assert.equal(closeRescue.entities[0].status,'alive','being near an ally through a wall does not stop the bot before it finds a doorway');
const temporary={x:0,z:0,w:3,d:.25,y:0,h:2.6,wall:99};const withWall=[temporary];const wallRoute=findRoute({x:0,z:6},{x:0,z:-6},withWall);assert.ok(wallRoute.length>1);
previous={x:0,z:6};for(const point of wallRoute){assert.ok(clearRoute(previous,point,withWall),'bot route avoids a temporary player barrier');previous=point}
console.log('Game tests passed: solo/squad, damage, revival, cover, reload, input deduplication, doors, camera, landing, zone, bot rescue and house detours');
