import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {nearbyWeaponLoot,nearbyWeaponItems,setupPickupPrompt,setupNearbyWeapons,loadAutoPickup,saveAutoPickup,WEAPON_PICKUP_RANGE} from '../public/loot-pickup.mjs';
import {makeMatch,act,setInput,tick,colliders} from '../public/engine.mjs';
import {WEAPONS} from '../public/rules.mjs';
import worker from '../server/worker.mjs';
import {localDatabase} from './local-db.mjs';

function arena(educational=false){const m=makeMatch({educational,humans:[{id:'a'},{id:'b'}]});m.drop=0;m.loot=[];m.entities=m.entities.slice(0,2);const[a,b]=m.entities;Object.assign(a,{x:0,y:0,z:0});Object.assign(b,{x:0,y:0,z:-20});return{m,a,b}}
const item=(id,weapon,x,z=0,y=0)=>({id,type:'weapon',weapon,x,z,y});
const {m,a}=arena();m.loot=[item(1,2,3.9),item(2,3,2.8)];assert.equal(WEAPON_PICKUP_RANGE,4);assert.equal(nearbyWeaponLoot(m,a,colliders(m)).id,2);act(m,a,'pickup',1);assert.equal(a.weapon,2,'the explicit displayed item wins even if another gun is closer');assert.ok(m.loot.some(i=>i.id===2));const previous=a.weapon;act(m,a,'pickup',1);assert.equal(a.weapon,previous,'a claimed item never silently substitutes a different gun');assert.equal(m.events.at(-1).type,'pickup-miss');
const reach=arena();reach.m.loot=[item(10,2,4.01)];act(reach.m,reach.a,'pickup',10);assert.equal(reach.a.weapons[2].owned,false);reach.m.loot[0].x=4;act(reach.m,reach.a,'pickup',10);assert.equal(reach.a.weapon,2,'the inclusive range boundary is consistent with the HUD');
const blocked=arena();blocked.m.loot=[item(20,2,3)];blocked.m.walls=[{id:2,hp:100,life:20,parts:[{x:1.5,z:0,w:.2,d:2,y:0,h:3}]}];assert.equal(nearbyWeaponLoot(blocked.m,blocked.a,colliders(blocked.m)),null);act(blocked.m,blocked.a,'pickup',20);assert.equal(blocked.a.weapons[2].owned,false,'expanded range cannot grab through walls');blocked.m.walls=[];blocked.m.loot[0].y=3;assert.equal(nearbyWeaponLoot(blocked.m,blocked.a,colliders(blocked.m)),null,'items on a different floor are inaccessible');
const lesson=arena(true);lesson.m.loot=[item(30,0,.4),item(31,3,3.5)];assert.equal(nearbyWeaponLoot(lesson.m,lesson.a,colliders(lesson.m)).id,31,'educational duplicates cannot hide a collectible new gun');act(lesson.m,lesson.a,'pickup',30);assert.equal(lesson.a.weapons[0].reserve,0);assert.equal(lesson.m.loot.length,2,'duplicate guns cannot bypass question ammo rewards');
const duplicate=arena();duplicate.a.weapons[0].reserve=360;duplicate.m.loot=[item(40,0,.3),item(41,4,3.7)];assert.equal(nearbyWeaponLoot(duplicate.m,duplicate.a,colliders(duplicate.m)).id,41);duplicate.a.weapons[0].reserve=340;act(duplicate.m,duplicate.a,'pickup',40);assert.equal(duplicate.a.weapons[0].reserve,360);assert.equal(duplicate.a.weapon,0);
const state=arena();state.m.loot=[item(50,2,2)];for(const status of['down','dead']){state.a.status=status;assert.equal(nearbyWeaponLoot(state.m,state.a,colliders(state.m)),null)}state.a.status='alive';state.m.drop=1;assert.equal(nearbyWeaponLoot(state.m,state.a,colliders(state.m)),null);state.m.drop=0;state.m.state='ended';assert.equal(nearbyWeaponLoot(state.m,state.a,colliders(state.m)),null);
const race=arena();race.b.x=0;race.b.z=0;race.m.loot=[item(60,2,3)];setInput(race.m,race.a.id,{actions:[{seq:1,type:'pickup',index:60}]});setInput(race.m,race.b.id,{actions:[{seq:1,type:'pickup',index:60}]});assert.equal(race.m.events.filter(e=>e.type==='pickup').length,1);assert.equal(race.a.weapons[2].owned,true);assert.equal(race.b.weapons[2].owned,false);setInput(race.m,race.a.id,{actions:[{seq:1,type:'pickup',index:60}]});assert.equal(race.m.events.filter(e=>e.type==='pickup').length,1,'replayed actions cannot duplicate a weapon');
const deliberate=arena();deliberate.m.loot=[item(70,2,0)];tick(deliberate.m,.04);assert.equal(deliberate.a.weapon,0,'walking never replaces a held gun');
const automatic=arena(true);automatic.a.reload=1;automatic.m.loot=[item(71,2,1.8),item(72,3,1.9),item(73,0,.1)];setInput(automatic.m,automatic.a.id,{autoPickup:true});tick(automatic.m,.04);assert.equal(automatic.a.weapons[2].owned,true);assert.equal(automatic.a.weapon,0,'auto pickup fills a slot without switching the held gun');assert.ok(automatic.a.reload>0,'automatic collection does not interrupt a reload');assert.equal(automatic.a.weapons[0].reserve,0,'educational duplicate ammo stays unavailable');automatic.m.loot[0].x=1;tick(automatic.m,.04);assert.equal(automatic.a.weapons[3].owned,false,'automatic pickup never replaces an occupied slot');
const disabled=arena();disabled.m.loot=[item(74,2,.5)];setInput(disabled.m,disabled.a.id,{autoPickup:false});tick(disabled.m,.04);assert.equal(disabled.a.weapons[2].owned,false);setInput(disabled.m,disabled.a.id,{autoPickup:'true'});tick(disabled.m,.04);assert.equal(disabled.a.weapons[2].owned,false,'only an explicit boolean enables auto pickup');
const storage={value:null,getItem(){return this.value},setItem(key,value){this.value=value}};assert.equal(loadAutoPickup(storage),true);saveAutoPickup(storage,false);assert.equal(loadAutoPickup(storage),false);saveAutoPickup(storage,true);assert.equal(loadAutoPickup(storage),true);assert.equal(loadAutoPickup({getItem(){throw Error('blocked')}}),true);
const button={hidden:true,disabled:false,listeners:{},name:{textContent:''},hint:{textContent:''},querySelector(s){return s==='b'?this.name:this.hint},setAttribute(name,value){this[name]=value},addEventListener(type,fn){this.listeners[type]=fn}};let clock=0,empty=0;const picked=[];
const prompt=setupPickupPrompt({button,onPickup:id=>picked.push(id),onEmpty:()=>empty++,now:()=>clock});prompt.update(item(80,2,3.9),deliberate.a,true);assert.equal(button.hidden,false);assert.match(button.name.textContent,/3.9 ม/);assert.match(button.hint.textContent,/แตะ/);let stopped=false;button.listeners.pointerdown({button:0,pointerType:'touch',preventDefault(){},stopPropagation(){stopped=true}});assert.equal(stopped,true);assert.deepEqual(picked,[80]);prompt.update(item(81,3,2),deliberate.a,true);button.onclick();assert.deepEqual(picked,[80],'the later click cannot pick the newly displayed item');clock=400;prompt.update(item(81,3,2),deliberate.a);assert.equal(button.disabled,false);button.onclick();assert.deepEqual(picked,[80,81],'keyboard activation still works');clock=800;prompt.update(null,deliberate.a);prompt.pick();assert.equal(empty,1);
class Node{constructor(){this.children=[];this.listeners={}}append(...nodes){this.children.push(...nodes)}replaceChildren(){this.children=[]}addEventListener(type,fn){this.listeners[type]=fn}setAttribute(name,value){this[name]=value}focus(){this.focused=true}}
const toggle=new Node(),panel=new Node(),list=new Node(),closeButton=new Node();let queued=[],shelf;const shelfPrompt=setupPickupPrompt({button:{...button,listeners:{}},now:()=>clock,onPickup:id=>{shelf.close();queued.push(id)}});shelf=setupNearbyWeapons({toggle,panel,list,closeButton,prompt:shelfPrompt,create:()=>new Node(),now:()=>clock,onClose:()=>{queued=[]}});
const nearby=nearbyWeaponItems({...deliberate.m,loot:[item(90,2,3),item(91,3,1)]},deliberate.a,colliders(deliberate.m));shelf.update(nearby,deliberate.a);toggle.onclick();assert.equal(shelf.open,true);assert.equal(closeButton.focused,true);const chosen=list.children[1];chosen.listeners.pointerdown({button:0,preventDefault(){},stopPropagation(){}});assert.deepEqual(queued,[90],'selecting a farther row commits its ID after closing/resetting controls');assert.equal(shelf.open,false);chosen.onclick();assert.deepEqual(queued,[90],'row click does not duplicate pointer pickup');clock=1200;shelf.update(nearby,deliberate.a);assert.equal(list.children[1],chosen,'position updates preserve focused row nodes');shelf.toggle();shelf.update([],deliberate.a);assert.equal(shelf.open,false);assert.equal(toggle.hidden,true);
const css=await readFile('public/mobile.css','utf8');assert.match(css,/#hud #pickup-weapon\{z-index:7;/,'pickup sits above the look surface');assert.match(css,/body\.touch #hud #pickup-weapon\{[^}]*178px/,'pickup clears the aim/fire buttons in both orientations');
// Run through the actual online packet sanitizer and persisted room, not just
// the engine: a loot ID is not a weapon index and must survive sanitization.
const DB=await localDatabase();
try{
 const call=async(operation,data)=>{const response=await worker.fetch(new Request('https://test.example/api/rooms/'+operation,{method:'POST',headers:{Origin:'https://test.example'},body:JSON.stringify(data)}),{DB});assert.ok(response.ok);return response.json()};
 const host=await call('create',{mode:'solo'}),auth={code:host.code,token:host.token};await call('start',auth);
 async function mutate(fn){const row=await DB.prepare('SELECT data FROM rooms WHERE code=?').bind(host.code).first(),room=JSON.parse(row.data);fn(room);await DB.prepare('UPDATE rooms SET data=?,revision=revision+1 WHERE code=?').bind(JSON.stringify(room),host.code).run()}
 await mutate(room=>{room.lastTick=Date.now()-200;room.match.drop=0;const me=room.match.entities.find(e=>e.id===host.id);Object.assign(me,{x:0,y:0,z:0});room.match.loot=[item(200,2,3.8),item(500,9,.2)]});
 const online=await call('poll',{...auth,controls:{actions:[{seq:1,type:'pickup',index:200}]}});assert.equal(online.match.entities.find(e=>e.id===host.id).weapon,2,'online pickup honors the shown loot ID above the weapon-index range');assert.ok(online.match.loot.some(l=>l.id===500));
 await mutate(room=>room.lastTick=Date.now()-200);const malformed=await call('poll',{...auth,controls:{actions:[{seq:2,type:'pickup',index:'500'}]}});assert.equal(malformed.match.entities.find(e=>e.id===host.id).weapon,2,'invalid explicit IDs cannot fall back to another gun');assert.ok(malformed.match.loot.some(l=>l.id===500));
 await mutate(room=>{room.lastTick=Date.now()-200;const me=room.match.entities.find(e=>e.id===host.id);me.weapons[2].owned=false;me.weapon=0;room.match.loot=[item(600,4,1.5)]});const onlineAuto=await call('poll',{...auth,controls:{autoPickup:true}});const autoActor=onlineAuto.match.entities.find(e=>e.id===host.id);assert.equal(autoActor.weapons[4].owned,true,'auto preference survives the online sanitizer');assert.equal(autoActor.weapon,0);
}finally{DB.close()}
console.log('Pickup passed: 4 m reach, exact selected item, duplicate filtering, educational ammo protection, walls/floors, state checks, races/replays, deliberate swaps and single-press touch/keyboard prompt');
